version: '3.8'

services:
  whatsapp-service:
    build: .
    container_name: whatsapp-web-service
    restart: unless-stopped
    volumes:
      # Persist WhatsApp session data
      - ./session_data:/app/.wwebjs_auth
      # Optional: mount logs directory
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - TZ=UTC
      - API_KEY=my_great_api_key
      - PORT=3000
      # Proxy configuration (optional)
      # Format: http://username:password@host:port or https://username:password@host:port
      #- PROXY_URL=https://user-spucrxuesb-country-il-city-tel_aviv-sessionduration-60:at8d8wE=4qfHlpX2xU@gate.decodo.com:10001
    ports:
      - "127.0.0.1:3000:3000"

    # Security options
    security_opt:
      - no-new-privileges:true
    cap_add:
      - SYS_ADMIN

    # Resource limits - increased for media processing
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
