version: '3.8'

services:
  whatsapp-service:
    build: .
    container_name: whatsapp-web-service
    restart: unless-stopped
    volumes:
      # Persist WhatsApp session data
      - ./session_data:/app/.wwebjs_auth
      # Optional: mount logs directory
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - TZ=UTC
      - PORT=3000
      - CHROME_EXECUTABLE_PATH=/usr/bin/google-chrome
    ports:
      - "127.0.0.1:3000:3000"

    # Security options
    security_opt:
      - no-new-privileges:true
    cap_add:
      - SYS_ADMIN

    # Resource limits - increased for media processing
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
