version: '3.8'

services:
  whatsapp-service:
    build: .
    container_name: whatsapp-web-service
    restart: unless-stopped
    volumes:
      # Persist WhatsApp session data
      - ./session_data:/app/.wwebjs_auth
      # Optional: mount logs directory
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - TZ=UTC
      - API_KEY=my_great_api_key
      - PORT=3000
      # Proxy configuration (optional)
      # Format: http://username:password@host:port or https://username:password@host:port
      - PROXY_URL=${PROXY_URL:-}
    ports:
      - "127.0.0.1:3000:3000"

    # Security options
    security_opt:
      - no-new-privileges:true
    cap_add:
      - SYS_ADMIN

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  session_data:
    driver: local
